
MERGE INTO HR_DATALAKE.PRODUCTION.EMPLOYEE_DETAIL AS T
USING (
    SELECT *
    FROM (
        SELECT S.*, ROW_NUMBER() OVER (PARTITION BY EMPLOYEE_ID ORDER BY METADATA$ROW_ID DESC) AS rn
        FROM HR_DATALAKE.STAGING.EMPLOYEE_DETAIL_STREAM AS S
        WHERE METADATA$ACTION IN ('INSERT', 'DELETE')
    )
    WHERE rn = 1
) AS S
ON T.EMPLOYEE_ID = S.EMPLOYEE_ID

WHEN MATCHED AND S.METADATA$ACTION = 'DELETE' THEN
    DELETE

WHEN MATCHED AND S.METADATA$ACTION = 'INSERT' THEN
    UPDATE SET
        T.FIRST_NAME = S.FIRST_NAME,
        T.LAST_NAME = S.LAST_NAME,
        T.EMAIL = S.EMAIL,
        T.HIRE_DATE = S.HIRE_DATE,
        T.DEPARTMENT_NAME = S.DEPARTMENT_NAME,
        T.JOB_TITLE = S.JOB_TITLE,
        T.COST_CENTER = S.COST_CENTER,
        T.LOCATION = S.LOCATION,
        T.MANAGER_NAME = S.MANAGER_NAME,
        T.EMPLOYMENTSTATUS = S.EMPLOYMENTSTATUS,
        T.ISACTIVE = S.ISACTIVE

WHEN NOT MATCHED AND S.METADATA$ACTION = 'INSERT' THEN
    INSERT (
        EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, HIRE_DATE, DEPARTMENT_NAME, JOB_TITLE, COST_CENTER, LOCATION, MANAGER_NAME, EMPLOYMENTSTATUS, ISACTIVE
    )
    VALUES (
        S.EMPLOYEE_ID, S.FIRST_NAME, S.LAST_NAME, S.EMAIL, S.HIRE_DATE, S.DEPARTMENT_NAME, S.JOB_TITLE, S.COST_CENTER, S.LOCATION, S.MANAGER_NAME, S.EMPLOYMENTSTATUS, S.ISACTIVE
    );
