INSERT INTO HR_DATALAKE.STAGING.EMPLOYEE_DETAIL (
    EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, HIRE_DATE, DEPARTMENT_NAME, JOB_TITLE, COST_CENTER, LOCATION, MANAGER_NAME, EMPLOYMENTSTATUS, ISACTIVE
) VALUES
(1008, 'Liam', 'Anderson', 'liam.anderson@corp.com', '2024-03-20', 'Operations', 'Supply Chain Analyst', 'CC106', 'Denver', 'Karen White', 'Full-Time', TRUE);
